// Personajes
export const characters = [
  {
    id: "1",
    name: "AgusZ",
    image: "/AgusZ.jpg",
    avatar: "/AgusZ.png",
    position: 16,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "2",
    name: "Boby Pleura",
    image: "/Conejo.jpeg",
    avatar: "/Conejo.png",
    position: 14,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "3",
    name: "Coreana",
    image: "/Coreana.jpg",
    avatar: "/Coreana.png",
    position: 13,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "4",
    name: "Coreano",
    image: "/Coreano.jpg",
    avatar: "/Coreano.png",
    position: 10,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "5",
    name: "El Padrino",
    image: "/Chris.jpg",
    avatar: "/Chris.png",
    position: 6,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "6",
    name: "Equiii",
    image: "/Equi.jpg",
    avatar: "/Equi.png",
    position: 2,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "7",
    name: "Jack Sparrow",
    image: "/Pipo.jpg",
    avatar: "/Pipo.png",
    position: 5,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "8",
    name: "Joe",
    image: "/Joe.jpg",
    avatar: "/Joe.png",
    position: 1,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "9",
    name: "Jorge Rial",
    image: "/Pablo.jpg",
    avatar: "/Pablo.png",
    position: 4,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "10",
    name: "Lepi+",
    image: "/Lepi.jpg",
    avatar: "/Lepi.png",
    position: 9,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "11",
    name: "Lokito",
    image: "/Lokito.jpg",
    avatar: "/Lokito.png",
    position: 7,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "12",
    name: "Masita",
    image: "/Masita.jpg",
    avatar: "/Chueko.png",
    position: 8,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "13",
    name: "Mirtha Legrand",
    image: "/Mirtha.jpg",
    avatar: "/Marcos.png",
    position: 11,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "14",
    name: "Pato",
    image: "/Pato.jpg",
    avatar: "/Pato.png",
    position: 15,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "15",
    name: "Pochoclo Mágico",
    image: "/Pocho.jpg",
    avatar: "/Pocho.png",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "16",
    name: "Xene",
    image: "/Xene.jpg",
    avatar: "/Xene.png",
    position: 12,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
];

// Mapas
export const maps = [
  {
    id: "1",
    name: "Aztec",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/7/74/De_aztec0017_Bombsite_A-3rd_view.png/revision/latest/scale-to-width-down/1000?cb=20130224090414",
    logo: "https://static.wikia.nocookie.net/cswikia/images/5/56/Map_icon_de_aztec.png/revision/latest?cb=20220903174703",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/a/a6/De_aztec_radar.png/revision/latest?cb=20220903174556",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "2",
    name: "Castle",
    image: "https://images.gamebanana.com/img/ss/mods/532b01b286040.jpg",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar: "no tiene",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "3",
    name: "Cbble",
    image:
      "https://images.gamebanana.com/img/embeddables/Mod_304430_sd_image.jpg?1626165178",
    logo: "https://static.wikia.nocookie.net/cswikia/images/2/21/Set_cobblestone.png/revision/latest?cb=20210928184414",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/a/a2/De_cbble_radar.png/revision/latest?cb=20190427135317",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "4",
    name: "Chateau",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/3/3b/Css_chateau_big.jpg/revision/latest?cb=20131101232832",
    logo: "https://static.wikia.nocookie.net/cswikia/images/2/21/Set_cobblestone.png/revision/latest?cb=20210928184414",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/0/0b/Css-maps-chateau-overview.jpg/revision/latest/scale-to-width-down/1000?cb=20140221184457",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "5",
    name: "Dust",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/d/da/1.6_Dust_A_Site.jpg/revision/latest/scale-to-width-down/1000?cb=20140903235343",
    logo: "https://static.wikia.nocookie.net/cswikia/images/1/10/Csgo_map_icon_de_shortdust.png/revision/latest?cb=20230901190753",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/b/bd/Dust_overview_csgo.png/revision/latest/scale-to-width-down/1000?cb=20220903174426",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "6",
    name: "Dust2",
    image: "https://scmapdb.wdfiles.com/local--files/map:pvp-dust2/1.jpg",
    logo: "https://static.wikia.nocookie.net/cswikia/images/d/db/Map_icon_de_dust2.png/revision/latest?cb=20230901185539",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/0/0f/Cs2_dust2_overview.png/revision/latest/scale-to-width-down/1000?cb=20230323162128",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "7",
    name: "Forge",
    image: "https://images.gamebanana.com/img/ss/mods/50b6ec2a7f731.jpg",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar: "no tiene",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "8",
    name: "Inferno",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/f/f5/De_inferno0005_Bombsite_B_2nd_view.png/revision/latest/scale-to-width-down/1000?cb=20130210200425",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/1/11/CS2_inferno_radar.png/revision/latest?cb=20230901123108",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "9",
    name: "Mirage",
    image: "https://4evergaming.com.ar/storage/maps/cs16/de_mirage.jpg",
    logo: "https://static.wikia.nocookie.net/cswikia/images/9/96/Set_mirage.png/revision/latest?cb=20230901185633",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/9/95/Cs2_mirage_radar.png/revision/latest?cb=20231020111431",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "10",
    name: "Nuke",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/3/36/De_nuke0006_Side_Yard-2nd_view.png/revision/latest/scale-to-width-down/1000?cb=20130214192618",
    logo: "https://static.wikia.nocookie.net/cswikia/images/e/ef/Set_nuke_2.png/revision/latest?cb=20230901185652",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/8/8f/Cs2_nuke_radar.png/revision/latest?cb=20231020111944 & https://static.wikia.nocookie.net/cswikia/images/e/e5/De_nuke_lower_radar.png/revision/latest?cb=20180928185435",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "11",
    name: "Piranesi",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/9/95/2014-02-20_00013.jpg/revision/latest/scale-to-width-down/1000?cb=20140220214510",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar: "no tiene",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "12",
    name: "Rats",
    image:
      "https://www.gamemaps.com/img/addons/cs/ss/de_rats_12636_1.jpg?1443731026",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar: "no tiene",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "13",
    name: "Rats3",
    image: "https://images.gamebanana.com/img/ss/mods/52c9366e44dc5.jpg",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar: "no tiene",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "14",
    name: "Survivor",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/5/5c/De_survivor_Airplane_crash_site_Bombsite_A.png/revision/latest/scale-to-width-down/1000?cb=20140629203414",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/8/8e/De_survivor_overview.png/revision/latest/scale-to-width-down/1000?cb=20141216135721",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "15",
    name: "Torn",
    image: "https://images.gamebanana.com/img/ss/mods/4ff5860af24ba.jpg",
    logo: "https://static.wikia.nocookie.net/cswikia/images/0/0a/CS2_inferno_logo.png/revision/latest?cb=20230901170051",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/7/7e/De_torn_cz_overview.png/revision/latest/scale-to-width-down/1000?cb=20140630225747",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "16",
    name: "Train",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/b/b5/De_train0020_Bombsite_B-2nd_view.png/revision/latest/scale-to-width-down/1000?cb=20130301194448",
    logo: "https://static.wikia.nocookie.net/cswikia/images/6/60/Set_train.png/revision/latest?cb=20211005232814",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/c/c0/De_train_radar.png/revision/latest?cb=20190427135318",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "17",
    name: "Tuscan",
    image:
      "https://steamuserimages-a.akamaihd.net/ugc/1638704086716180757/4A86F90D0FFA96A446297965F6E9D3850C3E1936/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false",
    logo: "https://static.wikia.nocookie.net/cswikia/images/4/4d/Map_icon_de_tuscan.png/revision/latest?cb=20220816232337",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/3/33/Csgo_radar_de_tuscan.png/revision/latest?cb=20220816232337",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
  {
    id: "18",
    name: "Vertigo",
    image:
      "https://static.wikia.nocookie.net/cswikia/images/3/3a/De_vertigo0003_Ramp-4th_view.png/revision/latest/scale-to-width-down/1000?cb=20130214184013",
    logo: "https://static.wikia.nocookie.net/cswikia/images/4/46/Vertigo-logo-new.png/revision/latest?cb=20230901185803",
    radar:
      "https://static.wikia.nocookie.net/cswikia/images/3/35/De_vertigo_radar.png/revision/latest?cb=20240524233147 & https://static.wikia.nocookie.net/cswikia/images/e/ea/De_vertigo_lower_radar.png/revision/latest?cb=20240524233051",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
];
