// Personajes
export const characters = [
  {
    id: "1",
    name: "AgusZ",
    image: "/AgusZ.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "2",
    name: "Boby Pleura",
    image: "/Conejo.jpeg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "3",
    name: "Coreana",
    image: "/Coreana.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "4",
    name: "Coreano",
    image: "/Coreano.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "5",
    name: "El Padrino",
    image: "/Chris.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "6",
    name: "Equiii",
    image: "/Equi.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "7",
    name: "Jack Sparrow",
    image: "/Pipo.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "8",
    name: "Joe",
    image: "/Joe.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "9",
    name: "Jorge Rial",
    image: "/Pablo.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "10",
    name: "Lepi+",
    image: "/Lepi.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "11",
    name: "Lokito",
    image: "/Lokito.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "12",
    name: "Masita",
    image: "/Masita.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "13",
    name: "Mirtha Legrand",
    image: "/Mirtha.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "14",
    name: "Pato",
    image: "/Pato.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "15",
    name: "Pochoclo Mágico",
    image: "/Pocho.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
  {
    id: "16",
    name: "Xene",
    image: "/Xene.jpg",
    avatar: "",
    position: 3,
    played: 70,
    win: 40,
    lose: 20,
    draw: 10,
    kills: 150,
    deaths: 100,
    total: 50,
    best_map: "Dust2",
    worst_map: "Vertigo",
    best_position: 1,
    worst_position: 10,
    kills_record: 26,
    death_record: 20,
  },
];

// Mapas
export const maps = [
  {
    id: "1",
    name: "de_aztec",
    image: "",
    avatar: "",
    plays: 20,
    tt_wins: 5,
    ct_wins: 15,
    best_player: "Equiii",
    worst_player: "Mirtha Legrand",
    death_record: -15,
    kill_record: 20,
  },
];
